
POST http://localhost:3000/user/registerclient
Content-Type: application/json

{
  "username": "clientUsername",
  "email": "client@example.com",
  "numTel": "123456789",
  "password": "clientPassword"
}


POST http://localhost:3000/user/loginclient
Content-Type: application/json

{
  "username": "clientUsername",
  "password": "clientPassword"
}


POST http://localhost:3000/recoverPassBySms
Content-Type: application/json

{
    "phone": "your_phone_number_here"
}


POST http://localhost:3000/sendOTP
Content-Type: application/json

{
  "numTel": "12345678"
}


POST http://localhost:3000/verifyOTP
Content-Type: application/json

{
  "numTel": "12345678",
  "otp": "123456"
}

GET http://localhost:3000/user/




GET http://localhost:3000/user/userEmail

PUT http://localhost:3000/user/:id/update
Content-Type: application/json

{
  "username": "newUsername",
  "email": "newEmail@example.com",
  "numTel": "12345678",
  "password": "newPassword",
  "role": "Client"
}


DELETE http://localhost:3000/:id/delete


PUT http://localhost:3000/:id/ban

### Delete User
//DELETE http://localhost:3000/user/userId/delete


POST http://localhost:3000/user/reset
Content-Type: application/json

{
    "email": "client1@example.com"
}


POST http://localhost:3000/user/forgot
Content-Type: application/json

{
    "email": "client1@example.com",
    "newPassword": "newpassword123",
    "confirmPassword": "newpassword123"
}


PUT http://localhost:3000/user/change
Content-Type: application/json

{
    "email": "client1@example.com",
    "oldPassword": "password123",
    "newPassword": "newpassword123",
    "confirmPassword": "newpassword123"
}


POST http://localhost:3000/user/registerclientSub
Content-Type: application/json

{
    "UserName": "clientSub1",
    "email": "clientsub1@example.com",
    "password": "password123"
}


POST http://localhost:3000/user/loginclientSub
Content-Type: application/json
{
  "username": "clientUsername",
  "password": "clientPassword"
}


POST http://localhost:3000/user/verify
Content-Type: application/json

{
    "resetCode": "1234",  
    "email": "client1@example.com"  
}

GET http://localhost:3000/user/Speicialities

GET http://localhost:3000/uploads/INSERT_FILENAME_HERE.jpg


PATCH http://localhost:3000/user/updatePicture
Content-Type: multipart/form-data

Content-Disposition: form-data; name="picture"; filename="profile-picture.jpg"
Content-Type: image/jpeg
GET http://localhost:3000/logout

POST http://localhost:3000/user/parse-pdf


POST http://localhost:3000/user/update-skills

{
  "userId": "your_user_id_here",
  "skills": ["skill1", "skill2", "skill3"]
}

GET  http://localhost:3000/user/user-skills/:userId


GET http://localhost:3000/user/:id